name: Tự Động Cập Nhật Sản Phẩm Shopee Affiliate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    # 1. Nâng cấp từ @v3 lên @v4 để chạy Node.js mới nhất
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Nâng cấp từ @v4 lên @v5 để tương thích Node.js mới nhất
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Cài đặt thư viện pandas và requests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    # 4. Kích hoạt file code Python để cào lướt dữ liệu
    - name: Run filter script
      run: python filter_datafeed.py

    # 5. Tự động Commit file json mới và Push ngược lại lên GitHub Pages
    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add shopee_products.json
        git diff-index --quiet HEAD || git commit -m "Auto-update Shopee products data"
        git push
